//  ._______.___________________.___________________.___________________.___________________._______;
//  proto.go
    package main

    import ( "dmcs/lib"; "fmt"; "google.golang.org/protobuf/proto"; "log"; )

    func main() {
        lib.Hello_main()

        user_out := &User {
            Userid: 111,
            Name:   "User1",
            Email:  "user1@gmail.com",
            Tel:    "1111111111",
        }
        res, err := proto.Marshal( user_out )
        if err != nil {
            log.Fatal("Marshal Error", err)
        }
        fmt.Printf("Marshalling Results: %v \n", res)

        user_in := &User{}
        err = proto.Unmarshal(res, user_in)
        if err != nil {
            log.Fatal("Unmarshalling Error", err)
        }
        fmt.Printf("Unmarshalling Results: %v \n", user_in)

        // Print with Getters generated by protoc
        fmt.Printf("Getters:\n  %d \n  %s \n", user_in.GetUserid(), user_in.GetName())
    }

